#!/bin/sh

# default Python interpreter is 'python' from your $PATH; set the $PYTHON
# environment variable to override it
: ${PYTHON:=python}
export PYTHONPATH="$(dirname $0)/..:$PYTHONPATH"

exec "$PYTHON" -m sllurp.access ${1+"$@"} -n 100 -M WISP5 -T 7140 192.168.178.21
